from enum import IntEnum

PREPARED_TIMEOUT = 10
COMMIT_ACK_TIMEOUT = 10
TRANSACTION_SIZE = 1
ACTIVE_TRANSACTIONS_LIMIT = 2
NUMBER_OF_COHORTS = 1

# Database constants
INSERT_SQL = "INSERT INTO TRANSACTION_LOG (ID, STATE, COHORTS) VALUES (%s, %s, %s)"
DELETE_SQL = "DELETE FROM TRANSACTION_LOG where ID = "
SELECT_SQL = "SELECT * from TRANSACTION_LOG"

class State(IntEnum):
    INITIATED = 0
    PREPARE = 1
    PREPARED = 2
    COMMIT = 3
    ABORT = 4
    ACK = 5
