#!/usr/bin/bash

mkdir -p test1

python3 coordinator.py 3 "test1" >> test1/coordinator.log &
echo "Started coordinator"
python3 Cohort.py -p 5433 -q 0 -c >> test1/cohort1.log &
echo "Started cohort1"
python3 Cohort.py -p 5434 -q 1 -c >> test1/cohort2.log &
echo "Started cohort2"
python3 Cohort.py -p 5435 -q 2 -c >> test1/cohort3.log &
echo "Started cohort3"
python3 coordinator.py 3 "test1" >> test1/coordinator.log &
sleep 15
python3 database_state_verifier.py
echo "Test complete. Please check the logs under the 'test1' directory"
